#release configuration
#Thu Apr 23 02:05:07 CDT 2026
projectVersionPolicyId=default
project.scm.io.scif\:scifio.connection=scm\:git\:https\://github.com/scifio/scifio
project.scm.io.scif\:scifio.developerConnection=scm\:git\:git@github.com\:scifio/scifio
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.dev.io.scif\:scifio=0.49.1-SNAPSHOT
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.rel.io.scif\:scifio=0.49.0
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/scifio/scifio
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.scm.io.scif\:scifio.tag=HEAD
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=scifio-0.49.0
project.scm.io.scif\:scifio.url=https\://github.com/scifio/scifio
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
